/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cs2263_hw01;

import org.apache.commons.cli.*;

public class App {

    //method

    public static String getHelp() {
        String bold = "\033[0;1m";
        String clear = "\033[0;0m";
        String help = bold + "NAME\t\t" + clear + "Expression Evaluator\n\n" +
                        bold + "DESCRIPTION\t" + clear + "This program evaluates mathematical expressions.\n\n" +
                bold + "OPTIONS\t" + clear + "\n" +
                "\t-h, --help\t\tDisplays this help message.\n" +
                "\t-b, --batch  <file>\tAllows for batch processing of expressions through an input file.\n" +
                "\t-o, --output <file>\tOutputs the evaluators data to a file.\n\n" +
                "Copyright 2022 Scott Brown";
        return help;
    }

    public static void main(String[] args) {
        Options options = new Options();

        options.addOption(Option.builder("h")
                .required(false)
                .desc("This is the help command.")
                .longOpt("help")
                .build());

        options.addOption(Option.builder("b")
                .required(false)
                .desc("This is the batch import command.")
                .longOpt("batch")
                .hasArg()
                .build());

        options.addOption(Option.builder("o")
                .required(false)
                .desc("This is the output file command.")
                .longOpt("output")
                .hasArg()
                .build());

        CommandLineParser parser = new DefaultParser();

        try {
            CommandLine cmd = parser.parse(options, args);

            if (cmd.hasOption("h")) {
                System.out.println(getHelp());
            }
            else if (cmd.hasOption("b") || cmd.hasOption("o")) {
                if (cmd.hasOption("b")) {
                    String batch = cmd.getOptionValue("b");
                    System.out.println("Batch value: " + batch);
                }
                if (cmd.hasOption("o")) {
                    String output = cmd.getOptionValue("o");
                    System.out.println("Output value: " + output);
                }
            }
        }
        catch (ParseException pe) {
                System.out.println("Parse Error. Bad argument or missing required argument.");
        }
    }
}